### PR TITLE
Move symplify/packages/autowire-array-parameter source here

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I just added code analysis workflow and it seems github action is not starting, could you verify it?

**Comment by TomasVotruba** [comment]
Same here.. Feel free to merge these as you go :+1:

**Comment by samsonasik** [comment]
@TomasVotruba github action still not running; could you enable it?

**Comment by TomasVotruba** [comment]
Done :+1:

**Comment by samsonasik** [comment]
@TomasVotruba thank you, it seems running now

**Comment by samsonasik** [comment]
@TomasVotruba it seems there is split symplify-kernel issue, even the packages/symplify-kernel composer.json updated, see https://github.com/symplify/symplify/pull/4553#discussion_r1094447994 , could you verify? Thank you.

**Comment by TomasVotruba** [comment]
I think this package should not depend on the symplify kernel, but on the symfony kernel directly. Could you decouple it from here?

**Comment by samsonasik** [comment]
This package doesn't depend on symplify-kernel, symplify-kernel does. See https://github.com/symplify/symplify-kernel/blob/4c2b4915942e73df92e4365bea67d68af4d13a86/composer.json#L10

Do you think the `AutowireArrayParameterCompilerPass` need to be copied to symplify-kernel ? see the usage on AbstractSymplifyKernel 

https://github.com/symplify/symplify-kernel/blob/4c2b4915942e73df92e4365bea67d68af4d13a86/src/HttpKernel/AbstractSymplifyKernel.php#L11

**Comment by TomasVotruba** [comment]
I see. In that case it should be required in symplify-kernel.

**Comment by samsonasik** [comment]
Current symplify split seems not working, see https://github.com/symplify/symplify/actions/runs/4074326681/jobs/7019339731#step:4:3

so I guess we can apply directly in splitted symplify-kernel?

**Comment by TomasVotruba** [comment]
Yeah, that's why I think we should refactor from it :) The API is a bit unstable with git upgdates on Github Actions.

Feel free to split all packages at once and make symplify/symplify obsolete.

**Comment by samsonasik** [comment]
Let's restart build.

**Comment by samsonasik** [comment]
@TomasVotruba it seems still error, the interdependencies seems cause it:

```
Your requirements could not be resolved to an installable set of packages.
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symplify/symplify-kernel dev-main requires symplify/autowire-array-parameter ^11.2 -> satisfiable by symplify/autowire-array-parameter[dev-main, 11.2.x-dev (alias of dev-main)] from composer repo (https://repo.packagist.org/) but symplify/autowire-array-parameter is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.
    - symplify/symplify-kernel 11.2.x-dev is an alias of symplify/symplify-kernel dev-main and thus requires it to be installed too.
    - Root composer.json requires symplify/symplify-kernel ^11.2 -> satisfiable by symplify/symplify-kernel[11.2.x-dev (alias of dev-main)].


  Problem 1
    - symplify/symplify-kernel dev-main requires symplify/autowire-array-parameter ^11.2 -> satisfiable by symplify/autowire-array-parameter[dev-main, 11.2.x-dev (alias of dev-main)] from composer repo (https://repo.packagist.org/) but symplify/autowire-array-parameter is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.
    - symplify/symplify-kernel 11.2.x-dev is an alias of symplify/symplify-kernel dev-main and thus requires it to be installed too.
    - Root composer.json requires symplify/symplify-kernel ^11.2 -> satisfiable by symplify/symplify-kernel[11.2.x-dev (alias of dev-main)].
    - 
  ```

The solution is possibly copy `AutowireArrayParameterCompilerPass` and its related classes there, like in rector-src was:

- https://github.com/rectorphp/rector-src/pull/3150

wdyt?

**Comment by samsonasik** [comment]
Let's [set COMPOSER_ROOT_VERSION](https://github.com/symplify/autowire-array-parameter/pull/1/commits/3a6d0f4d2e37bed4c768a13bd8def38c609d501c)

**Comment by samsonasik** [comment]
@TomasVotruba It works 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's merge and tag it.

**Comment by samsonasik** [comment]
@TomasVotruba merged and tagged 11.1.26 for it https://github.com/symplify/autowire-array-parameter/releases/tag/11.1.26

**Pull request merged**
